wget 'https://upload.wikimedia.org/wikipedia/commons/1/1d/A_Black_Hole%E2%80%99s_Dinner_is_Fast_Approaching_-_Part_2.ogv'
wget 'https://upload.wikimedia.org/wikipedia/commons/9/96/Curiosity%27s_Seven_Minutes_of_Terror.ogv'
wget 'https://upload.wikimedia.org/wikipedia/commons/7/7a/Descenso_en_ascensor_el_Peral%2C_Valpara%C3%ADso.webm'
wget 'https://upload.wikimedia.org/wikipedia/commons/c/c1/Jarry_-_M%C3%A9tro_de_Montr%C3%A9al_%281280%C3%97720%29.ogv'
wget 'https://upload.wikimedia.org/wikipedia/commons/5/50/Lutra_lutra_grooming.ogv'
wget 'https://upload.wikimedia.org/wikipedia/commons/c/c9/X-47B_Lands_at_Naval_Air_Staion_Patuxent_River.webm'
